/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ActividadController;
import controlador.ExceptionController;
import controlador.NominasController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Actividad;

/**
 *
 * @author inmar
 */
public class JPanelAltaBajaActividades extends javax.swing.JPanel {

    /**
     * Creates new form jPanelNuevaActividad
     */
    public JPanelAltaBajaActividades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbNombreact = new javax.swing.JLabel();
        lbPrecoact = new javax.swing.JLabel();
        lbTareasignada = new javax.swing.JLabel();
        txtNombreAct = new javax.swing.JTextField();
        txtPrecoActv = new javax.swing.JTextField();
        txtTareaAsig = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIDACTIVIDAD = new javax.swing.JTextField();
        btDardeBaja = new javax.swing.JButton();
        btGuardarAvtividad = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALTA DE ACTIVIDADES");

        lbNombreact.setText("NOMBRE: ");
        lbNombreact.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbPrecoact.setText("PRECIO: ");
        lbPrecoact.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbTareasignada.setText("ASIGNADA TAREA: ");
        lbTareasignada.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtPrecoActv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActvActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BAJA DE ACTIVIDADES");

        jLabel3.setText("ID ACTIVIDAD");

        btDardeBaja.setText("DAR DE BAJA");
        btDardeBaja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btDardeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDardeBajaActionPerformed(evt);
            }
        });

        btGuardarAvtividad.setText("GUARDAR");
        btGuardarAvtividad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btGuardarAvtividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarAvtividadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNombreact)
                    .addComponent(lbPrecoact)
                    .addComponent(lbTareasignada))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrecoActv, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTareaAsig)
                    .addComponent(txtNombreAct, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btDardeBaja))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btGuardarAvtividad))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addComponent(txtIDACTIVIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreact)
                    .addComponent(txtNombreAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecoact)
                    .addComponent(txtPrecoActv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTareasignada)
                    .addComponent(txtTareaAsig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btGuardarAvtividad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIDACTIVIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btDardeBaja)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecoActvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActvActionPerformed

    private void btDardeBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDardeBajaActionPerformed
        /**
         * Necesito saber el precio de la actividad que estoy eliminando
         * - Consulto en bd la nomina para coger su precio
         * - Una vez que tenga el precio, tengo que actualizar la nómina
         */
        String consulta = "delete from ACTIVIDAD where ID_ACT = " + txtIDACTIVIDAD.getText();
        String precio="SELECT * FROM ACTIVIDAD WHERE ID_ACT="+ txtIDACTIVIDAD.getText();
        
        //String consulta2="SELECT * FROM NOMINA WHERE ID
        try {
            ActividadController.crearConsultaActividad(precio);
            Actividad actividad= ActividadController.devolverActividad();
            String consultaNomina= "UPDATE NOMINA SET CALCULO_ACTIVIDADES= (CALCULO_ACTIVIDADES - "+ actividad.getPrecio()+"), SALARIOTOTAL=(SALARIOBASE+CALCULO_ACTIVIDADES) WHERE ID = "+actividad.getIdNomina();
            NominasController.ejecutaUpdate(consulta);
            
            try{
                ActividadController.ejecutaUpdate(consultaNomina);
            }catch(SQLException ex) {
                ExceptionController.getError(6, "JPanelAltaBajaActividades.btDardeBajaActionPerformed()");
            }
            JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente la activiadad");
        } catch (SQLException ex) {
            ExceptionController.getError(6, "JPanelAltaBajaActividades.btDardeBajaActionPerformed()");
        }
    }//GEN-LAST:event_btDardeBajaActionPerformed

    private void btGuardarAvtividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarAvtividadActionPerformed
        String nombre = this.txtNombreAct.getText();
        float precio = Float.valueOf(this.txtPrecoActv.getText());
        int tarea = Integer.valueOf(this.txtTareaAsig.getText());
        int nuevoId = ActividadController.ultimoId();

        String consulta = "INSERT INTO ACTIVIDAD VALUES (" + nuevoId + ", '" + nombre + "', " + precio + ", " + tarea + ", null)";
        try {
            ActividadController.ejecutaUpdate(consulta);
            JOptionPane.showMessageDialog(null, "Se ha insertado correctamente la activiadad");
        } catch (SQLException ex) {
            //Logger.getLogger(JPanelAltaBajaActividades.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Se ha producido un error al intentar insertar la actividad");
        }
    }//GEN-LAST:event_btGuardarAvtividadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDardeBaja;
    private javax.swing.JButton btGuardarAvtividad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbNombreact;
    private javax.swing.JLabel lbPrecoact;
    private javax.swing.JLabel lbTareasignada;
    private javax.swing.JTextField txtIDACTIVIDAD;
    private javax.swing.JTextField txtNombreAct;
    private javax.swing.JTextField txtPrecoActv;
    private javax.swing.JTextField txtTareaAsig;
    // End of variables declaration//GEN-END:variables
}
